# Generated by Django 6.1 on 2026-08-06 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='broadcastslot',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ready', 'Ready'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='presenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='schedule_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='technical_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='interview_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='social_post',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='story_outline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('assigned', 'Assigned'), ('writing', 'Writing'), ('editing', 'Editing'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='idea', max_length=20),
        ),
        migrations.CreateModel(
            name='AudioArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.CharField(max_length=300)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('is_backup_verified', models.BooleanField(default=False)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_archives', to='newsroom.story')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('script_approved', 'Script Approved'), ('on_air', 'On Air'), ('technical_check', 'Technical Check'), ('archive_published', 'Archive Published')], max_length=60)),
                ('message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_logs', to='newsroom.program')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='newsroom.studio'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('station_manager', 'Station Manager'), ('editor', 'Editor'), ('producer', 'Producer'), ('presenter', 'Presenter'), ('reporter', 'Reporter'), ('technician', 'Technician / Audio Engineer'), ('administrator', 'Administrator')], max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ReporterProfile',
        ),
    ]
