# Generated by Django 6.1 on 2026-08-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0003_remove_audioarchive_file_path_audioarchive_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
